### ISSUE TITLE
If is empty "atto_styles | config" crashes javascript, tested in moodle 4.1.1 and atto_styles versión v4.1-r2.

### ISSUE THREAD

**Issue by moodlexabi** [moodleuulm/moodle-atto_styles#36]
If is empty "atto_styles | config" crashes javascript, tested in moodle 4.1.1 and atto_styles versión v4.1-r2.

```
yui_combo.php?m/1688989846/atto_table/button/button-min.js&m/1688989846/atto_clear/button/button-min.js&m/1688989846/atto_undo/button/button-min.js&m/1688989846/atto_accessibilitychecker/button/button-min.js&m/1688989846/atto_accessibilityhelper/button/button-min.js&m/1688989846/atto_wiris/button/button-min.js&3.17.2/promise/promise-min.js&m/1688989846/atto_html/beautify/beautify-min.js&m/1688989846/atto_html/codemirror/codemirror-min.js&m/1688989846/atto_html/button/button-min.js&m/1688989846/atto_morefontcolors/button/button-min.js&m/1688989846/atto_fontfamily/button/button-min.js&m/1688989846/atto_morebackcolors/button/button-min.js&m/1688989846/atto_hr/button/button-min.js&m/1688989846/atto_styles/button/button-min.js&m/1688989846/atto_cloze/button/button-min.js&m/1688989846/atto_emojipicker/button/button-min.js:77 Uncaught TypeError: Cannot read properties of null (reading 'type')
    at YUI.<anonymous> (yui_combo.php?m/1688989846/atto_table/button/button-min.js&m/1688989846/atto_clear/button/button-min.js&m/1688989846/atto_undo/button/button-min.js&m/1688989846/atto_accessibilitychecker/button/button-min.js&m/1688989846/atto_accessibilityhelper/button/button-min.js&m/1688989846/atto_wiris/button/button-min.js&3.17.2/promise/promise-min.js&m/1688989846/atto_html/beautify/beautify-min.js&m/1688989846/atto_html/codemirror/codemirror-min.js&m/1688989846/atto_html/button/button-min.js&m/1688989846/atto_morefontcolors/button/button-min.js&m/1688989846/atto_fontfamily/button/button-min.js&m/1688989846/atto_morebackcolors/button/button-min.js&m/1688989846/atto_hr/button/button-min.js&m/1688989846/atto_styles/button/button-min.js&m/1688989846/atto_cloze/button/button-min.js&m/1688989846/atto_emojipicker/button/button-min.js:77:316)
    at Array.forEach (<anonymous>)
    at m.each.m.forEach (yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:10:1339)
    at n.initializer (yui_combo.php?m/1688989846/atto_table/button/button-min.js&m/1688989846/atto_clear/button/button-min.js&m/1688989846/atto_undo/button/button-min.js&m/1688989846/atto_accessibilitychecker/button/button-min.js&m/1688989846/atto_accessibilityhelper/button/button-min.js&m/1688989846/atto_wiris/button/button-min.js&3.17.2/promise/promise-min.js&m/1688989846/atto_html/beautify/beautify-min.js&m/1688989846/atto_html/codemirror/codemirror-min.js&m/1688989846/atto_html/button/button-min.js&m/1688989846/atto_morefontcolors/button/button-min.js&m/1688989846/atto_fontfamily/button/button-min.js&m/1688989846/atto_morebackcolors/button/button-min.js&m/1688989846/atto_hr/button/button-min.js&m/1688989846/atto_styles/button/button-min.js&m/1688989846/atto_cloze/button/button-min.js&m/1688989846/atto_emojipicker/button/button-min.js:77:230)
    at n._initHierarchy (yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:279:3762)
    at n._baseInit (yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:279:1086)
    at n.init (yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:311:694)
    at n._initBase (yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:279:948)
    at n.v (yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:279:95)
    at n.o (yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:319:50)
```

Here is a patch to fix in lib.php
[lib.php.patch](https://github.com/moodle-an-hochschulen/moodle-atto_styles/files/12229347/lib.php.patch)

**Comment by abias** [comment]
Many thanks for your input and discussion here.
Unfortunately, it has never been processed finally which makes me very sorry.

I am closing this issue now as this plugin has reached end of life as stated on https://github.com/moodle-an-hochschulen/moodle-atto_styles?tab=readme-ov-file#state-of-the-plugin.
